"""Samples table.

Revision ID: e9b2d4451e70
Revises: 9d9ca8017587
Create Date: 2023-09-11 14:57:42.031779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b2d4451e70'
down_revision = '9d9ca8017587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_line', sa.String(), nullable=False),
    sa.Column('gene_ko', sa.String(), nullable=False),
    sa.Column('treatment', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    # ### end Alembic commands ###
